### PR TITLE
feat: endpoint to handle fulfillment_completed events

### PR DESCRIPTION
**Pull request by blefebvre**
This PR implements the `POST /event/fulfillment` endpoint as detailed in the API spec.

Provides a method to handle `fulfillment_completed` events from the Fulfillment Gateway. Events are queued for processing onto the provided SQS queue URL.

A sample event in the expected format can be found in `test/controllers/event/sample-hoolihan-event.json`

Ticket: https://jira.corp.adobe.com/browse/SITES-19428

### CODE REVIEW

**Review by solaris007 — APPROVED** [review]
Great contribution, thank you @blefebvre ! I have just _nitpick_ comments.

**Comment by blefebvre** [comment]
Thank you @solaris007 for the review and suggestions.

**Review by solaris007 — APPROVED** [review]
LGTM

**Pull request merged**
