### PR TITLE
fix: get sites slack command

### PR DESCRIPTION
**Pull request by alinarublea**
Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

Thanks for contributing!

### CODE REVIEW

**Review by iuliag — COMMENTED** [review]
Could you describe the issue and the fix?
My understanding is that each block will be now posted in a separate message, whereas before the list of blocks was grouped in 25 blocks per message. But I might be wrong :)

What is the max size a Slack message can have, is there a limitation that we could break even while posting a single block per message?

**Comment by alinarublea** [comment]
The issues is get sites slack command is returning an error.
Coralogix logs error is: ```
'invalid_blocks',
errors: [
'no more than 25 items allowed [json-pointer:/blocks/1/elements]'
],
response_metadata: { messages: [Array], scopes: [Array], acceptedScopes: [Array] }
}
}timestamp:2024-03-05T13:53:02.531Z

```
Yesterday I tried to send chunks of max 25 blocks, but as you say the problem might be also the size of a block.
I send a message using the dev bot and it looks ok to send 1 block at the time because we have the thread referenced, but
I will investigate more.

**Comment by iuliag** [comment]
I'd suggest looking at the slack limitations (e.g. the maximum of 25 is mentioned for the elements in an action block https://api.slack.com/reference/block-kit/blocks#actions) and the consumers of the `sendMessageBlocks` function.
https://github.com/adobe/spacecat-api-service/blob/main/src/support/slack/commands/get-sites.js#L111C10-L111C34 seems to introduce a lot of additional button blocks for pagination purpose.

**Comment by iuliag** [comment]
@alinarublea I'd suggest we close this as https://github.com/adobe/spacecat-api-service/pull/214 is merged.

**Pull request closed without merging**
