### PR TITLE
fix: slack format messages

### PR DESCRIPTION
**Pull request by AndreiAlexandruParaschiv**
The slack format messages for the commands as
- Github repo added for 
- Successfully added new site 

have special char in the url, see:
https://cq-dev.slack.com/archives/C05B53SRX7V/p1711473214258659?thread_ts=1711472698.177529&cid=C05B53SRX7V
https://cq-dev.slack.com/archives/C05B53SRX7V/p1711476855457419?thread_ts=1711472698.177529&cid=C05B53SRX7V
Screenshot 2024-03-28 at 14 46 30

~Removed bold format (* *) and special char to keep the consistency across other messages.~
https://api.slack.com/reference/surfaces/formatting#linking-urls - on how to have bold messages with links

slack example : `"text": ":white_check_mark: *Successfully added new site <www.neacaisa.ro|www.neacaisa.ro>*"`

## Change Management

```yaml
cm-assessment: v1
changeType: standard
impact: unnoticeable
risk: minor
changeApprovedBy: ["Iulia Grumaz", "Dominique Jäggi"]
rationale: "Auto-added baseline (no PR assessment present at CI time); refine via the cmr skill if this change is higher-impact."
```

### CODE REVIEW

**Comment by solaris007** [comment]
@AndreiAlexandruParaschiv originally these characters made the text appear bold. instead of removing the bold we should investigate why it is no longer rendered as such?

**Comment by AndreiAlexandruParaschiv** [comment]
> @AndreiAlexandruParaschiv originally these characters made the text appear bold. instead of removing the bold we should investigate why it is no longer rendered as such?

Some other messages like :  _Successfully updated the live_  don't  have * * (bold), so should all the success messages be with bold then? I can then adjust the pr for it

**Comment by solaris007** [comment]
@AndreiAlexandruParaschiv yes, the first line should usually be bold (heading...).

Could you also investigate to not have links unfurled for the `get site` command?

**Comment by solaris007** [comment]
> Could you also investigate to not have links unfurled for the get site command?
@AndreiAlexandruParaschiv did you find a solution for this?

**Comment by AndreiAlexandruParaschiv** [comment]
> > Could you also investigate to not have links unfurled for the get site command?
> 
> @AndreiAlexandruParaschiv did you find a solution for this?

@solaris007  Yes, passing `unfurl_links: false` is one solution and another is that slackapi never unfurls links where the label is a complete substring of your URL minus the protocol (if a message contains a link to http://example.com with the label example.com, the link will not be unfurled),

**Review by iuliag — APPROVED** [review]

**Review by solaris007 — APPROVED** [review]

**Pull request merged**
