### PR TITLE
docs(api): cwv schema changes to support groups and site metrics

### PR DESCRIPTION
**Pull request by ekremney**
cwv schema changes to support groups and site metrics.

how it looks like:

Screenshot 2024-11-26 at 10 18 13

**Example JSON:**

```json
[
  {
    "type": "group",
    "name": "Homepage Group",
    "pattern": "https://www.aem.live/home*",
    "pageviews": 4620,
    "metrics": [
      {
        "deviceType": "mobile",
        "pageviews": 2134,
        "lcp": 2099.7,
        "lcpCount": 9,
        "cls": 0.02066,
        "clsCount": 7,
        "inp": 12,
        "inpCount": 3,
        "ttfb": 520.45,
        "ttfbCount": 18
      },
      {
        "deviceType": "desktop",
        "pageviews": 2486,
        "lcp": 1800.5,
        "lcpCount": 8,
        "cls": 0.015,
        "clsCount": 6,
        "inp": 10,
        "inpCount": 2,
        "ttfb": 480.3,
        "ttfbCount": 15
      }
    ]
  },
  {
    "type": "group",
    "name": "Developer Pages",
    "pattern": "https://www.aem.live/developer/*",
    "pageviews": 3000,
    "metrics": [
      {
        "deviceType": "mobile",
        "pageviews": 2000,
        "lcp": 612.1,
        "lcpCount": 4,
        "cls": 0.001,
        "clsCount": 4,
        "inp": 20,
        "inpCount": 2,
        "ttfb": 122.9,
        "ttfbCount": 4
      },
      {
        "deviceType": "desktop",
        "pageviews": 1000,
        "lcp": 490.2,
        "lcpCount": 3,
        "cls": 0.0008,
        "clsCount": 3,
        "inp": 18,
        "inpCount": 1,
        "ttfb": 115.7,
        "ttfbCount": 3
      }
    ]
  },
  {
    "type": "url",
    "url": "https://www.aem.live/home",
    "pageviews": 2620,
    "metrics": [
      {
        "deviceType": "mobile",
        "pageviews": 1620,
        "lcp": 2099.7,
        "lcpCount": 9,
        "cls": 0.02066,
        "clsCount": 7,
        "inp": 12,
        "inpCount": 3,
        "ttfb": 520.45,
        "ttfbCount": 18
      },
      {
        "deviceType": "desktop",
        "pageviews": 1000,
        "lcp": 1800.5,
        "lcpCount": 8,
        "cls": 0.015,
        "clsCount": 6,
        "inp": 10,
        "inpCount": 2,
        "ttfb": 480.3,
        "ttfbCount": 15
      }
    ]
  },
  {
    "type": "url",
    "url": "https://www.aem.live/developer/block-collection",
    "pageviews": 2000,
    "metrics": [
      {
        "deviceType": "mobile",
        "pageviews": 500,
        "lcp": 512.1,
        "lcpCount": 4,
        "cls": 0.0005,
        "clsCount": 4,
        "inp": 20,
        "inpCount": 2,
        "ttfb": 122.9,
        "ttfbCount": 4
      },
      {
        "deviceType": "desktop",
        "pageviews": 1500,
        "lcp": 490.2,
        "lcpCount": 3,
        "cls": 0.0008,
        "clsCount": 3,
        "inp": 18,
        "inpCount": 1,
        "ttfb": 115.7,
        "ttfbCount": 3
      }
    ]
  }
]

```

### CODE REVIEW

**Review by rpapani — APPROVED** [review]
Looks good to me 👍

**Comment by ekremney** [comment]
> Should we create a new HTTP entry point, for example, that would return the new response, as well as a new method at the in the RUMClient at the code level? Or is it acceptable to modify the current implementation?

@naydav this is only for documentation purposes. Front end isn't consuming the audit results as of today anyway. However, once the metrics per device type and the grouping is implemented, we need to update the reporting worker which is reporting CWV degradations to slack

**Comment by ekremney** [comment]
PSA: this PR is only for documentation purposes. This PR will be merged when the CWV audit is improved with pattern and device type grouping on prod

**Pull request merged**
