### PR TITLE
fix: Update API docs to match implementation

### PR DESCRIPTION
**Pull request by blefebvre**
Removes `scrollToBottom` and `customHeaders` from the spec as import options. Updates naming of `pageLoadTimeout`.

### CODE REVIEW

**Review by atopper — APPROVED** [review]
👍 
I didn't realize `customHeaders` was not available.  I assume they'll be added later to handle authentication for sites that need users to be logged in.

**Comment by blefebvre** [comment]
We do support `customHeaders` but not as a part of `options`:

Screenshot 2024-09-11 at 4 16 24 PM

**Comment by atopper** [comment]
Got it.  It was the limited PR view that threw me.  Perfect!

**Review by swetabar — APPROVED** [review]

**Pull request merged**
