### PR TITLE
feat: opt-out updateExcludedURLs

### PR DESCRIPTION
**Pull request by AndreiAlexandruParaschiv**
https://jira.corp.adobe.com/browse/SITES-22463

PATH `{endpoint}/{siteId}/{auditType}`  where auditType is broken-backlinks

Body
```
{
  "excludedURLs": [
	"https://www.neacaisaslr.com",
	"https://www.marinica.com",
	"https://www.tudorica.com",
	"https://www.misulica.com"
   ]
}
```

Response: 
```
{
	"disabled": true,
	"excludedURLs": [
	   "https://www.neacaisaslr.com",
	   "https://www.marinica.com",
	   "https://www.tudorica.com",
	   "https://www.misulica.com""
	]
}
```

To remove the excludedURLs, send an empty array in the body

Disclaimer: tested it (a lot) on dev for siteId 7be95fa1-e532-410c-b6f8-6584ca92ac09

### CODE REVIEW

**Comment by iuliag** [comment]
```PATCH {endpoint}/{siteId}/{auditType}
'404':
        $ref: './responses.yaml#/404-audit-not-found'
```
The implementation does not seem to return any 404.

**Review by alinarublea — APPROVED** [review]

**Review by iuliag — APPROVED** [review]
👍🏻 
Do you validate anywhere that the strings passed in the excludedURLs array are valid URL format? If not, you should.

**Comment by AndreiAlexandruParaschiv** [comment]
> 👍🏻 Do you validate anywhere that the strings passed in the excludedURLs array are valid URL format? If not, you should.

Added `isValidUrl` function to validate the URLs and also added checks to return 404 for siteId and auditType

**Pull request merged**
